/**
 * SEO Policy — single source of truth for indexing and sitemap rules.
 *
 * Shared by:
 *   - astro.config.mjs          (the @astrojs/sitemap filter)
 *   - scripts/validate-seo.mjs  (deterministic SEO validation gate)
 *   - tests/seo-policy.spec.ts  (unit tests)
 *
 * Keeping the policy in one module ensures the sitemap and the validator that
 * checks it can never drift apart.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const BLOG_DIR = join(ROOT, 'src', 'content', 'blog');
const PAGES_DIR = join(ROOT, 'src', 'pages');

/** Extract the `tags` array from a blog file's YAML frontmatter. */
export function parseFrontmatterTags(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return [];
  const frontmatter = match[1];
  const tagLine = frontmatter
    .split('\n')
    .map((line) => line.trim())
    .find((line) => /^tags\s*:/.test(line));
  if (!tagLine) return [];
  const inline = tagLine.match(/\[([\s\S]*?)\]/);
  if (!inline) return [];
  return inline[1]
    .split(',')
    .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
    .filter(Boolean);
}

/** Count of posts per tag across the blog collection. */
export function getTagCounts() {
  const counts = new Map();
  for (const file of readdirSync(BLOG_DIR)) {
    if (!/\.(md|mdx)$/.test(file)) continue;
    for (const tag of parseFrontmatterTags(readFileSync(join(BLOG_DIR, file), 'utf-8'))) {
      counts.set(tag, (counts.get(tag) ?? 0) + 1);
    }
  }
  return Object.fromEntries([...counts.entries()].sort());
}

/**
 * Tag archive routes for tags with exactly one post. A single-entry archive
 * merely repeats one article card without meaningful unique context, so it is
 * `noindex` and excluded from the sitemap. This is derived from content so
 * archives become indexable automatically once they contain more than one post.
 */
export function getSingleEntryTagRoutes() {
  const counts = getTagCounts();
  return Object.keys(counts)
    .filter((tag) => counts[tag] === 1)
    .map((tag) => `/tags/${tag}/`);
}

/**
 * Routes generated by static pages that call Astro.redirect(...). Astro
 * renders these as meta-refresh documents; they are aliases, not content,
 * so they are noindex and excluded from the sitemap.
 */
let cachedRedirectRoutes = null;
function walkFiles(dir) {
  const results = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walkFiles(full));
    else if (entry.isFile() && entry.name.endsWith('.astro')) results.push(full);
  }
  return results;
}

export function getRedirectRoutes() {
  if (cachedRedirectRoutes) return cachedRedirectRoutes;
  const routes = [];
  for (const file of walkFiles(PAGES_DIR)) {
    if (!/Astro\.redirect\s*\(/.test(readFileSync(file, 'utf-8'))) continue;
    const rel = relative(PAGES_DIR, file)
      .replace(/\\/g, '/')
      .replace(/\.astro$/, '');
    const route = rel === 'index' ? '/' : `/${rel}/`;
    routes.push(route);
  }
  cachedRedirectRoutes = routes.sort();
  return cachedRedirectRoutes;
}

/** True when a pathname is a redirect alias rather than a content page. */
export function isRedirectRoute(pathname) {
  if (pathname.startsWith('/posts/')) return true;
  return getRedirectRoutes().includes(pathname);
}

/**
 * True when a pathname must be excluded from the XML sitemap.
 * Anything not excluded is expected to appear in the sitemap when it is an
 * indexable, built page.
 */
export function excludeFromSitemap(pathname) {
  if (pathname.startsWith('/lab/')) return true;
  if (pathname.startsWith('/posts/')) return true;
  if (pathname.startsWith('/search/')) return true;
  if (pathname.startsWith('/design-system/lab/')) return true;
  if (isRedirectRoute(pathname)) return true;
  return getSingleEntryTagRoutes().includes(pathname);
}
